### ISSUE TITLE
Send modmails created by AutoModerator to the CivcraftMods queue

### ISSUE THREAD

**Issue by ghost** [Civcraft/modmail_ticketmanager#11]
Newbie posts keep getting stuck in purgatory and since we have a fanciful ticket system, they end up not getting looked at ever.

**Comment by ttk2** [comment]
agreed

**Comment by Pentom** [comment]
Reviewed change request and there appears to be value here.

Change completed on the main modmail_ticketmanager repository (https://github.com/Pentom/modmail_ticketmanager).  It appears that you all have forked the modmail code to include civcraft / minecraft specific data.  Not adding this to the main repository as it does not fit with the overall theme for the script.  If you wish these changes, just have a developer merge my changes down to the civcraft branch or cherrypick the following two checksums:
2397cd333310e28f2cec044a825cc97a1d520e1c
d8e893f46fcf467ff700d480bfcba6f940afa831

Tested in my test suite and modmail bot usage myself.  Works appropriately with no unintended consequences.

Implementation Details:
New Configuration:
requestTrackerOptionalAuthorToQueueMapping = [['automoderator',1],['different_user_goes_here',1]] # This example has automod posts going to queue 1.  Can accept multiple author/queue tuples.

Things to remember:
    \* You need to make sure the bot has all rights to the new queue.
    \* You need to change the queue number for automoderator from 1 to whatever queue you wish to use for it.
    \* You need to decide if people who can access this queue should be able to access the custom field for replying.  If so, you will need to edit the custom field to change the 'Applies To' section to include this new queue.

**Comment by erocs** [comment]
> Not adding this to the main repository as it does not fit with the
> overall theme for the script

That's fine as I don't think that patch should be in our master for trading
with you.

**Comment by Pentom** [comment]
To the best of my knowledge, there is nothing more needed to satisfy this issue except merge in the changes mentioned above.  As such, will stop monitoring this particular issue and leave it to you all to adjust as needed.

Get my attention if you have any questions.

Thanks!

**Comment by erocs** [comment]
No worries, just split civcraft specific changes into the civcraft branch. Thanks!
