### ISSUE TITLE
SSL not properly configured. 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/modmail_ticketmanager#5]
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

**Comment by erocs** [comment]
I thought I already did that for RT on the jenkins box. As per that web
site:

To use the Python OpenSSL bindings instead, you’ll need to install the
required packages:

$ pip install pyopenssl ndg-httpsclient pyasn1

Once the packages are installed, you can tell urllib3 to switch the ssl
backend to PyOpenSSL withinject_into_urllib3():

import urllib3.contrib.pyopenssl
urllib3.contrib.pyopenssl.inject_into_urllib3()

**Comment by ttk2** [comment]
installed, so I add those includes at the stop of the script?

**Comment by erocs** [comment]
Line 110ish

**Comment by ttk2** [comment]
like this? if its right I will make a pull to the repo for the change.

import praw
import time
import sqlite3
import sys, traceback
import urllib3.contrib.pyopenssl
urllib3.contrib.pyopenssl.inject_into_urllib3()
from datetime import datetime
from datetime import timedelta
from pprint import pprint

**Comment by erocs** [comment]
If it works, sure. I can't remember if you have to import urllib3 before
importing pyopenssl.

**Comment by erocs** [comment]
This must work now.
