### ISSUE TITLE
Error when attempting to review modmail on line number 180

### ISSUE THREAD

**Issue by ttk2** [Civcraft/modmail_ticketmanager#6]
2015-04-28 12:59:54.746898 - Error when attempting to review modmail on line number 180.  Exception:  <class 'urllib2.URLError'>

I can't tell if this is because I configured somthing wrong or a bug.

**Comment by erocs** [comment]
Line 37, set debug to true and try again

**Comment by ttk2** [comment]
Waking... Processing modmail.
Logged into Reddit.
Found at least one item in modmail.
Checking if core message is handled yet.  Subject:  Too many alts
Core message not found in system.  Processing.
2015-04-28 15:46:23.685401 - Error when attempting to review modmail on
line number 180.  Exception:  <class 'urllib2.URLError'>
**\* print_tb:
  File "modmail_ticketmanager.py", line 180, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail,
inExtendedValidationMode)
**\* print_exception:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 180, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail,
inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 287, in processModMailRootMessage
    ticketId = createTicket(rootAuthor, rootSubject, rootBody,
rootResponseUrl)
URLError: <urlopen error [Errno 113] No route to host>
**\* print_exc:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 180, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail,
inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 287, in processModMailRootMessage
    ticketId = createTicket(rootAuthor, rootSubject, rootBody,
rootResponseUrl)
  File "modmail_ticketmanager.py", line 427, in createTicket
    response = resource.post(path='ticket/new', payload=content,)
  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 29,
in post
    return self.request('POST', path, payload, headers)
  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 46,
in request
    response = self.auth.open(req)
  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py",
line 59, in open
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py",
line 51, in login
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py",
line 114, in _login
    urllib2.Request(self.url, urllib.urlencode(data))
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 113] No route to host>
*_\* format_exc, first and last line:
Traceback (most recent call last):
URLError: <urlopen error [Errno 113] No route to host>
**\* format_exception:
['Traceback (most recent call last):\n', '  File
"modmail_ticketmanager.py", line 180, in processModMail\n
 shouldContinueProcessing = processModMailRootMessage(debug, mail,
inExtendedValidationMode)\n', '  File "modmail_ticketmanager.py", line 287,
in processModMailRootMessage\n    ticketId = createTicket(rootAuthor,
rootSubject, rootBody, rootResponseUrl)\n', '  File
"modmail_ticketmanager.py", line 427, in createTicket\n    response =
resource.post(path=\'ticket/new\', payload=content,)\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 29, in
post\n    return self.request(\'POST\', path, payload, headers)\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 46, in
request\n    response = self.auth.open(req)\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 59,
in open\n    self.login()\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 51,
in login\n    self._login()\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 114,
in _login\n    urllib2.Request(self.url, urllib.urlencode(data))\n', '
 File "/usr/lib/python2.7/urllib2.py", line 404, in open\n    response =
self._open(req, data)\n', '  File "/usr/lib/python2.7/urllib2.py", line
422, in _open\n    \'_open\', req)\n', '  File
"/usr/lib/python2.7/urllib2.py", line 382, in _call_chain\n    result =
func(_args)\n', '  File "/usr/lib/python2.7/urllib2.py", line 1214, in
http_open\n    return self.do_open(httplib.HTTPConnection, req)\n', '  File
"/usr/lib/python2.7/urllib2.py", line 1184, in do_open\n    raise
URLError(err)\n', 'URLError: <urlopen error [Errno 113] No route to
host>\n']
*_\* extract_tb:
[('modmail_ticketmanager.py', 180, 'processModMail',
'shouldContinueProcessing = processModMailRootMessage(debug, mail,
inExtendedValidationMode)'), ('modmail_ticketmanager.py', 287,
'processModMailRootMessage', 'ticketId = createTicket(rootAuthor,
rootSubject, rootBody, rootResponseUrl)'), ('modmail_ticketmanager.py',
427, 'createTicket', "response = resource.post(path='ticket/new',
payload=content,)"),
('/usr/local/lib/python2.7/dist-packages/rtkit/resource.py', 29, 'post',
"return self.request('POST', path, payload, headers)"),
('/usr/local/lib/python2.7/dist-packages/rtkit/resource.py', 46, 'request',
'response = self.auth.open(req)'),
('/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py', 59,
'open', 'self.login()'),
('/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py', 51,
'login', 'self._login()'),
('/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py', 114,
'_login', 'urllib2.Request(self.url, urllib.urlencode(data))'),
('/usr/lib/python2.7/urllib2.py', 404, 'open', 'response = self._open(req,
data)'), ('/usr/lib/python2.7/urllib2.py', 422, '_open', "'_open', req)"),
('/usr/lib/python2.7/urllib2.py', 382, '_call_chain', 'result =
func(_args)'), ('/usr/lib/python2.7/urllib2.py', 1214, 'http_open', 'return
self.do_open(httplib.HTTPConnection, req)'),
('/usr/lib/python2.7/urllib2.py', 1184, 'do_open', 'raise URLError(err)')]
*_\* format_tb:
['  File "modmail_ticketmanager.py", line 180, in processModMail\n
 shouldContinueProcessing = processModMailRootMessage(debug, mail,
inExtendedValidationMode)\n', '  File "modmail_ticketmanager.py", line 287,
in processModMailRootMessage\n    ticketId = createTicket(rootAuthor,
rootSubject, rootBody, rootResponseUrl)\n', '  File
"modmail_ticketmanager.py", line 427, in createTicket\n    response =
resource.post(path=\'ticket/new\', payload=content,)\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 29, in
post\n    return self.request(\'POST\', path, payload, headers)\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 46, in
request\n    response = self.auth.open(req)\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 59,
in open\n    self.login()\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 51,
in login\n    self._login()\n', '  File
"/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 114,
in _login\n    urllib2.Request(self.url, urllib.urlencode(data))\n', '
 File "/usr/lib/python2.7/urllib2.py", line 404, in open\n    response =
self._open(req, data)\n', '  File "/usr/lib/python2.7/urllib2.py", line
422, in _open\n    \'_open\', req)\n', '  File
"/usr/lib/python2.7/urllib2.py", line 382, in _call_chain\n    result =
func(_args)\n', '  File "/usr/lib/python2.7/urllib2.py", line 1214, in
http_open\n    return self.do_open(httplib.HTTPConnection, req)\n', '  File
"/usr/lib/python2.7/urllib2.py", line 1184, in do_open\n    raise
URLError(err)\n']
*_\* tb_lineno: 180
Modmail processed.  Sleeping...

looks like maybe it can't get to the API for RT

**Comment by erocs** [comment]
I suspect you didn't configure the script. Specifically line 69, but it
would be good to read it all over.

**Comment by ttk2** [comment]
requestTrackerRestApiUrl = 'http://192.168.25.129/rt/REST/1.0/' # Pretty
much your url + /Rest/1.0/

that's a local ip, so I figured it was some kind of loopback address,
should I just use rt.civcraft.co? That would open us up to domain
highjacking attacks.

I really should be able to figure out if that was a loopback address, IP
addressing is on my Networking Final next week.

**Comment by erocs** [comment]
RFC 1918 (http://tools.ietf.org/html/rfc1918) sets aside specific netblocks
for private network use. 192.168.0.0/16 is one of those. Loopback is
127.0.0.1. Yes point it at rt.civcraft.co. Any virtual web host is
susceptible to domain hijacking. If you want to host the DNS yourself, I
can transfer you the domain; not a problem.

**Comment by ttk2** [comment]
2015-04-28 17:16:26.969863 - Error when attempting to review modmail on line number 182.  Exception:  <type 'exceptions.ValueError'>
**\* print_tb:
  File "modmail_ticketmanager.py", line 182, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
**\* print_exception:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 182, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 289, in processModMailRootMessage
    ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)
ValueError: unknown url type: rt.civcraft.co/rt/REST/1.0/
**\* print_exc:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 182, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 289, in processModMailRootMessage
    ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)
  File "modmail_ticketmanager.py", line 429, in createTicket
    response = resource.post(path='ticket/new', payload=content,)
  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 29, in post
    return self.request('POST', path, payload, headers)
  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 46, in request
    response = self.auth.open(req)
  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 59, in open
    self.login()
  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 51, in login
    self._login()
  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 114, in _login
    urllib2.Request(self.url, urllib.urlencode(data))
  File "/usr/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: rt.civcraft.co/rt/REST/1.0/
**\* format_exc, first and last line:
Traceback (most recent call last):
ValueError: unknown url type: rt.civcraft.co/rt/REST/1.0/
**\* format_exception:
['Traceback (most recent call last):\n', '  File "modmail_ticketmanager.py", line 182, in processModMail\n    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)\n', '  File "modmail_ticketmanager.py", line 289, in processModMailRootMessage\n    ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)\n', '  File "modmail_ticketmanager.py", line 429, in createTicket\n    response = resource.post(path=\'ticket/new\', payload=content,)\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 29, in post\n    return self.request(\'POST\', path, payload, headers)\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 46, in request\n    response = self.auth.open(req)\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 59, in open\n    self.login()\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 51, in login\n    self._login()\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 114, in _login\n    urllib2.Request(self.url, urllib.urlencode(data))\n', '  File "/usr/lib/python2.7/urllib2.py", line 396, in open\n    protocol = req.get_type()\n', '  File "/usr/lib/python2.7/urllib2.py", line 258, in get_type\n    raise ValueError, "unknown url type: %s" % self.__original\n', 'ValueError: unknown url type: rt.civcraft.co/rt/REST/1.0/\n']
**\* extract_tb:
[('modmail_ticketmanager.py', 182, 'processModMail', 'shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)'), ('modmail_ticketmanager.py', 289, 'processModMailRootMessage', 'ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)'), ('modmail_ticketmanager.py', 429, 'createTicket', "response = resource.post(path='ticket/new', payload=content,)"), ('/usr/local/lib/python2.7/dist-packages/rtkit/resource.py', 29, 'post', "return self.request('POST', path, payload, headers)"), ('/usr/local/lib/python2.7/dist-packages/rtkit/resource.py', 46, 'request', 'response = self.auth.open(req)'), ('/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py', 59, 'open', 'self.login()'), ('/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py', 51, 'login', 'self._login()'), ('/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py', 114, '_login', 'urllib2.Request(self.url, urllib.urlencode(data))'), ('/usr/lib/python2.7/urllib2.py', 396, 'open', 'protocol = req.get_type()'), ('/usr/lib/python2.7/urllib2.py', 258, 'get_type', 'raise ValueError, "unknown url type: %s" % self.__original')]
**\* format_tb:
['  File "modmail_ticketmanager.py", line 182, in processModMail\n    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)\n', '  File "modmail_ticketmanager.py", line 289, in processModMailRootMessage\n    ticketId = createTicket(rootAuthor, rootSubject, rootBody, rootResponseUrl)\n', '  File "modmail_ticketmanager.py", line 429, in createTicket\n    response = resource.post(path=\'ticket/new\', payload=content,)\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 29, in post\n    return self.request(\'POST\', path, payload, headers)\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/resource.py", line 46, in request\n    response = self.auth.open(req)\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 59, in open\n    self.login()\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 51, in login\n    self._login()\n', '  File "/usr/local/lib/python2.7/dist-packages/rtkit/authenticators.py", line 114, in _login\n    urllib2.Request(self.url, urllib.urlencode(data))\n', '  File "/usr/lib/python2.7/urllib2.py", line 396, in open\n    protocol = req.get_type()\n', '  File "/usr/lib/python2.7/urllib2.py", line 258, in get_type\n    raise ValueError, "unknown url type: %s" % self.__original\n']
**\* tb_lineno: 182

and again, this time with the new domain.

**Comment by erocs** [comment]
That's a different error.

 unknown url type: rt.civcraft.co/rt/REST/1.0/

You need to keep the protocol specification intact.
http://rt.civcraft.co/rt/REST/1.0/

**Comment by ttk2** [comment]
Derp. Don't mind me. Missing the obvious is what happens when you post
between ksp launches. (My space plane keeps overheating and exploding at
mach ~2 trying to get mach 5 without committing jebicide)

**Comment by erocs** [comment]
Redirecting you to https://github.com/Pentom/modmail_ticketmanager/issues/4 for the new error
