### ISSUE TITLE
Assign certain tickets to users

### ISSUE THREAD

**Issue by rourke750** [Civcraft/modmail_ticketmanager#8]
I was wondering if for certain issues it would be possible to tag certain users so if it was relevant for them they could be included in the conversation while not needing full access to all mod mail stuff.

**Comment by erocs** [comment]
No clue if we can get RT setup to support that.

**Comment by Pentom** [comment]
@rourke750  Can you describe the problem you are trying to solve?  An example where this would be useful?

There are ways to grant access but its a pain and could involve some in depth user management and the easiest way may be to move the ticket to a queue that would allow the other mods (but not mail mods) to see it.  It would also need to make sure the modmail bot has full access to this other queue.

Regardless, its possible but I don't know that its worth the time setting this up.  Hence the example request.

**Comment by ttk2** [comment]
the example is this, we have low level mods that don't get much info, but
we sometimes have pretty trivial tickes (player lost armor, we confirm that
they lost it) that we can shuffle over to lower level mods to wrap up, I
don't think its enough of a usecase, but its worth looking at a bit.

**Comment by Pentom** [comment]
This is just an app configuration issue then not a modmail_ticketmanager issue.

To get the functionality you want, you should able to make the following changes:
- Create group called "Minimal Trust"
- Create a queue called "Minimal Trust Queue"
- Add group security rights for your "Admin" group and "Minimal Trust" group to be able to change the queue in the desired manner.
- Create an account in request tracker for the user you wish to have this limited access.  
- Add this user to the group "Minimal Trust"
- Edit a ticket and change its queue from General to "Minimal Trust"
- Log in with this user you created and validate that you cannot see items in the "General" queue but you can see the single ticket in the "Minimal Trust" queue <-- incredibly important.

You may have to play with security a bit and you absolutely -must- make sure that you are ok with the minimal trust users being able to edit the custom field for reddit replies.  If you arnt comfortable with that, then you need to deny that permission for the custom field to group minimal trust.

Anyway, suggest you use the request tracker public demo server to do some testing but its literally just a security configuration issue with two queues and group memberships.

**Comment by erocs** [comment]
@ttk2 I believe that's a different scenario from Rourke's. For yours, we'd just create a superfriend's queue and create a new ticket there detailing what was needed.

@rourke750 wants to be able to be added to specific modmail conversations that are technical in nature.

@Pentom A new queue is the best solution I've thought of too. Will the script scrape these tickets and still properly shuffle messages between it and modmail?

**Comment by Pentom** [comment]
@erocs yeah, first thing I looked at.  The queue is only used to determine where to -create- a ticket (initial queue), not where its being updated.  As long as modmailbot has the ability to update tickets in your other queues, you are fine.  Worth considering expanding its privileges just to guarantee you never create a queue and forget to do add privileges leading to modmailbot not being able to update.

**Comment by erocs** [comment]
Ok, setup the queues and tested permissions/functionality with a test user. Should be good to go.

**Comment by Pentom** [comment]
@erocs may want to make sure you go to the CustomField you added (modmail reply) and make sure that the "Applies To" tag (far upper left button when you have selected the custom field) has both your general and your super friend queues selected.  

If you want to verify it works fine, obvious answer is just to modmail yourself, move to superfriends, and try to comment after that and make sure it works fine.  Should.

**Comment by erocs** [comment]
Yup, the appropriate queues have the custom field available, thanks!
